INSERT INTO ARTICLE (TITLE, CONTENT) VALUES ('가가가가', '1111'); -- id=1
INSERT INTO ARTICLE (TITLE, CONTENT) VALUES ('나나나나', '2222'); -- id=2
INSERT INTO ARTICLE (TITLE, CONTENT) VALUES ('다다다다', '3333'); -- id=3

ALTER TABLE ARTICLE ALTER COLUMN ID RESTART WITH 4;
