INSERT INTO ARTICLE (TITLE, CONTENT) VALUES ('A', 'a'); -- id=1
INSERT INTO ARTICLE (TITLE, CONTENT) VALUES ('B', 'b'); -- id=2
INSERT INTO ARTICLE (TITLE, CONTENT) VALUES ('C', 'c'); -- id=3

ALTER TABLE ARTICLE ALTER COLUMN ID RESTART WITH 4;
